package com.vgleadsheets.strings

@Suppress("CyclomaticComplexMethod", "LongMethod")
fun VglsStringId.id(): Int = when (this) {
        VglsStringId.APP_NAME -> R.string.app_name
        VglsStringId.NAV_LABEL_HOME -> R.string.nav_label_home
        VglsStringId.NAV_LABEL_BROWSE -> R.string.nav_label_browse
        VglsStringId.NAV_LABEL_FAVORITE -> R.string.nav_label_favorite
        VglsStringId.NAV_LABEL_SEARCH -> R.string.nav_label_search
        VglsStringId.SCREEN_TITLE_PART_SELECTOR -> R.string.screen_title_parts
        VglsStringId.SCREEN_TITLE_BROWSE -> R.string.screen_title_browse
        VglsStringId.SCREEN_TITLE_BROWSE_GAMES -> R.string.screen_title_games
        VglsStringId.SCREEN_TITLE_BROWSE_COMPOSERS -> R.string.screen_title_composers
        VglsStringId.SCREEN_TITLE_BROWSE_TAGS -> R.string.screen_title_tags
        VglsStringId.SCREEN_TITLE_BROWSE_BY_TAG -> R.string.screen_title_by_tag
        VglsStringId.SCREEN_TITLE_BROWSE_SONGS_WITH_TAG -> R.string.screen_title_songs_with_tag
        VglsStringId.SCREEN_TITLE_BROWSE_ALL -> R.string.screen_title_all
        VglsStringId.SCREEN_TITLE_BROWSE_FAVORITES -> R.string.screen_title_favorites
        VglsStringId.SCREEN_TITLE_SEARCH -> R.string.screen_title_search
        VglsStringId.SCREEN_TITLE_SETTINGS -> R.string.screen_title_settings
        VglsStringId.SCREEN_TITLE_OFFLINE -> R.string.screen_title_offline
        VglsStringId.SCREEN_TITLE_UPDATES -> R.string.screen_title_updates
        VglsStringId.SCREEN_TITLE_LICENSES -> R.string.screen_title_licenses
        VglsStringId.SCREEN_TITLE_OFFLINE_UPDATES -> R.string.screen_title_offline_updates
        VglsStringId.SCREEN_SUBTITLE_SONG_DETAIL -> R.string.screen_subtitle_song_detail
        VglsStringId.SECTION_HEADER_SEARCH_SONGS -> R.string.section_header_search_songs
        VglsStringId.SECTION_HEADER_SEARCH_GAMES -> R.string.section_header_search_games
        VglsStringId.SECTION_HEADER_SEARCH_COMPOSERS -> R.string.section_header_search_composers
        VglsStringId.SECTION_HEADER_COMPOSERS_FROM_SONG -> R.string.section_header_composers_from_song
        VglsStringId.SECTION_HEADER_COMPOSERS_FROM_GAME -> R.string.section_header_composers_from_game
        VglsStringId.SECTION_HEADER_SONGS_FROM_GAME -> R.string.section_header_songs_from_game
        VglsStringId.SECTION_HEADER_SONGS_FROM_COMPOSER -> R.string.section_header_songs_from_composer
        VglsStringId.SECTION_HEADER_GAMES_FROM_SONG -> R.string.section_header_games_from_song
        VglsStringId.SECTION_HEADER_GAMES_FROM_COMPOSER -> R.string.section_header_games_from_composer
        VglsStringId.SECTION_HEADER_DIFFICULTY_FOR_SONG -> R.string.section_header_difficulty_for_song
        VglsStringId.SECTION_HEADER_ABOUT_SONG -> R.string.section_header_about_song
        VglsStringId.SECTION_HEADER_SETTINGS_DATA -> R.string.section_header_settings_data
        VglsStringId.SECTION_HEADER_SETTINGS_ABOUT -> R.string.section_header_settings_about
        VglsStringId.SECTION_HEADER_SETTINGS_DEBUG -> R.string.section_header_settings_debug
        VglsStringId.CTA_FAVORITE_ADD -> R.string.cta_favorite_add
        VglsStringId.CTA_FAVORITE_REMOVE -> R.string.cta_favorite_remove
        VglsStringId.CTA_OFFLINE_ADD -> R.string.cta_offline_add
        VglsStringId.CTA_OFFLINE_REMOVE -> R.string.cta_offline_remove
        VglsStringId.CTA_ALT_SELECT -> R.string.cta_alt_select
        VglsStringId.CTA_ALT_UNSELECT -> R.string.cta_alt_unselect
        VglsStringId.CTA_SEARCH_YOUTUBE -> R.string.cta_search_youtube
        VglsStringId.CTA_SEARCH -> R.string.cta_search
        VglsStringId.CTA_SEARCH_OTHER_QUERY -> R.string.cta_search_other_query
        VglsStringId.CTA_FAVORITES -> R.string.cta_favorites
        VglsStringId.CTA_OFFLINE -> R.string.cta_offline
        VglsStringId.LABEL_SONG_ALSO_KNOWN_AS -> R.string.label_song_also_known_as
        VglsStringId.HOME_SECTION_RECENT_SONGS -> R.string.home_section_recent_songs
        VglsStringId.HOME_SECTION_MOST_SONGS_GAMES -> R.string.home_section_most_songs_games
        VglsStringId.HOME_SECTION_MOST_SONGS_COMPOSERS -> R.string.home_section_most_songs_composers
        VglsStringId.HOME_SECTION_NO_PLAYS_SONGS -> R.string.home_section_no_plays_games
        VglsStringId.HOME_SECTION_MOST_PLAYS_GAMES -> R.string.home_section_most_plays_games
        VglsStringId.HOME_SECTION_MOST_PLAYS_SONGS -> R.string.home_section_most_plays_songs
        VglsStringId.HOME_SECTION_MOST_PLAYS_COMPOSERS -> R.string.home_section_most_plays_composers
        VglsStringId.HOME_SECTION_MOST_PLAYS_TAG_VALUES -> R.string.home_section_most_plays_tag_values
        VglsStringId.HOME_SECTION_RNG -> R.string.home_section_rng
        VglsStringId.HOME_ACTION_RANDOM_SONG -> R.string.home_action_random_song
        VglsStringId.HOME_ACTION_RANDOM_GAME -> R.string.home_action_random_game
        VglsStringId.HOME_ACTION_RANDOM_COMPOSER -> R.string.home_action_random_composer
        VglsStringId.BROWSE_LINK_OFFLINE -> R.string.browse_link_offline
        VglsStringId.BROWSE_LINK_FAVORITES -> R.string.browse_link_favorites
        VglsStringId.BROWSE_LINK_GAME -> R.string.browse_link_game
        VglsStringId.BROWSE_LINK_COMPOSER -> R.string.browse_link_composer
        VglsStringId.BROWSE_LINK_TAG -> R.string.browse_link_tag
        VglsStringId.BROWSE_LINK_DIFFICULTY -> R.string.browse_link_difficulty
        VglsStringId.BROWSE_LINK_SHEETS -> R.string.browse_link_sheets
        VglsStringId.BROWSE_LINK_PUBLISH_DATE -> R.string.browse_link_publish_date
        VglsStringId.PART_MID_C -> R.string.part_mid_c
        VglsStringId.PART_MID_B -> R.string.part_mid_b
        VglsStringId.PART_MID_E -> R.string.part_mid_e
        VglsStringId.PART_MID_F -> R.string.part_mid_f
        VglsStringId.PART_MID_G -> R.string.part_mid_g
        VglsStringId.PART_MID_ALTO -> R.string.part_mid_alto
        VglsStringId.PART_MID_BASS -> R.string.part_mid_bass
        VglsStringId.PART_MID_VOCAL -> R.string.part_mid_vocal
        VglsStringId.PART_LONG_C -> R.string.part_long_c
        VglsStringId.PART_LONG_B -> R.string.part_long_b
        VglsStringId.PART_LONG_E -> R.string.part_long_e
        VglsStringId.PART_LONG_F -> R.string.part_long_f
        VglsStringId.PART_LONG_G -> R.string.part_long_g
        VglsStringId.PART_LONG_ALTO -> R.string.part_long_alto
        VglsStringId.PART_LONG_BASS -> R.string.part_long_bass
        VglsStringId.PART_LONG_VOCAL -> R.string.part_long_vocal
        VglsStringId.SETTINGS_LABEL_CHECK_FOR_UPDATES -> R.string.label_settings_check_for_updates
        VglsStringId.SETTINGS_LABEL_OFFLINE -> R.string.label_settings_offline
        VglsStringId.SETTINGS_LABEL_CLEAR_USAGE -> R.string.label_settings_clear_usage
        VglsStringId.SETTINGS_LABEL_CLEAR_SHEETS -> R.string.label_settings_clear_sheets
        VglsStringId.SETTINGS_LABEL_KEEP_SCREEN_ON -> R.string.label_settings_keep_screen_on
        VglsStringId.SETTINGS_LABEL_LICENSES -> R.string.label_settings_license
        VglsStringId.SETTINGS_LABEL_WEBSITE -> R.string.label_settings_website
        VglsStringId.SETTINGS_LABEL_GIANT_BOMB -> R.string.label_settings_gb
        VglsStringId.SETTINGS_LABEL_PRIVACY -> R.string.label_settings_privacy
        VglsStringId.SETTINGS_LABEL_DEBUG_FAKE_API -> R.string.label_settings_debug_fake
        VglsStringId.SETTINGS_LABEL_DEBUG_DELAY -> R.string.label_settings_debug_delay
        VglsStringId.SETTINGS_LABEL_DEBUG_NAV_SNACKBARS -> R.string.label_settings_debug_show_nav_snackbars
        VglsStringId.SETTINGS_LABEL_DEBUG_RENDER_OVERLAY -> R.string.label_settings_debug_render_overlay
        VglsStringId.SETTINGS_LABEL_DEBUG_GENERATE_RECORDS -> R.string.label_settings_debug_generate_records
        VglsStringId.SETTINGS_LABEL_DEBUG_GENERATE_RECORDS_LEGACY -> R.string.label_settings_debug_generate_records_legacy
        VglsStringId.SETTINGS_LABEL_DEBUG_MIGRATE_RECORDS -> R.string.label_settings_debug_migrate_records
        VglsStringId.SETTINGS_LABEL_DEBUG_RESTART -> R.string.label_settings_debug_restart
        VglsStringId.SETTINGS_LABEL_APP_WHATS_NEW -> R.string.label_settings_whats_new
        VglsStringId.SETTINGS_LABEL_APP_BRANCH -> R.string.label_settings_branch
        VglsStringId.SETTINGS_LABEL_APP_VERSION_NAME -> R.string.label_settings_version_name
        VglsStringId.SETTINGS_LABEL_APP_VERSION_CODE -> R.string.label_settings_version_code
        VglsStringId.SETTINGS_LABEL_APP_BUILD_DATE -> R.string.label_settings_build_date
        VglsStringId.SETTINGS_LABEL_OFFLINE_UPDATES -> R.string.label_settings_offline_updates
        VglsStringId.SETTINGS_CAPTION_CLEAR_USAGE -> R.string.caption_settings_clear_usage
        VglsStringId.SETTINGS_CAPTION_CLEAR_SHEETS -> R.string.caption_settings_clear_sheets
        VglsStringId.SETTINGS_CAPTION_OFFLINE_UPDATES -> R.string.caption_settings_offline_updates
        VglsStringId.OFFLINE_UPDATE_FIELD_STATUS -> R.string.offline_update_field_status
        VglsStringId.OFFLINE_UPDATE_FIELD_SERVER_TIME -> R.string.offline_update_field_server_time
        VglsStringId.OFFLINE_UPDATE_FIELD_UPDATED_SONGS -> R.string.offline_update_field_updated_songs
        VglsStringId.OFFLINE_UPDATE_FIELD_SUCCESSFUL_OFFLINES -> R.string.offline_update_field_successful_offlines
        VglsStringId.OFFLINE_UPDATES_EMPTY -> R.string.offline_updates_empty
        VglsStringId.OFFLINE_UPDATES_ERROR -> R.string.offline_updates_error
        VglsStringId.NOTIF_TITLE_DB_UPDATE_SUCCESS -> R.string.notif_db_update_success
        VglsStringId.NOTIF_TITLE_APP_UPDATE_DEFAULT -> R.string.notif_app_update_default
        VglsStringId.NOTIF_TITLE_APP_UPDATE_FIRST_TIME -> R.string.notif_app_update_first
        VglsStringId.NOTIF_TITLE_APP_UPDATE_FIRST_SINCE_REMASTER -> R.string.notif_app_update_remaster
        VglsStringId.NOTIF_TITLE_APP_UPDATE_ERROR -> R.string.notif_app_update_error
        VglsStringId.SNACKBAR_SCREEN_OFF -> R.string.snack_screen_off
        VglsStringId.SNACKBAR_CTA_SCREEN_OFF -> R.string.snack_cta_screen_off
        VglsStringId.ERROR_API_UPDATE -> R.string.error_api_update
        VglsStringId.ERROR_DB_UPDATE -> R.string.error_db_update
        VglsStringId.ERROR_UPDATE_API_PREFIX -> R.string.error_update_api_prefix
        VglsStringId.ERROR_UPDATE_DB_PREFIX -> R.string.error_update_db_prefix
        VglsStringId.ERROR_UPDATE_REASON_OFFLINE -> R.string.error_update_reason_offline
        VglsStringId.ERROR_UPDATE_REASON_NO_INTERNET -> R.string.error_update_reason_no_internet
        VglsStringId.ERROR_UPDATE_REASON_API_UNREACHABLE -> R.string.error_update_reason_api_unreachable
        VglsStringId.ERROR_UPDATE_REASON_GENERIC -> R.string.error_update_reason_generic
        VglsStringId.ERROR_UPDATE_DB_REASON_GENERIC -> R.string.error_update_db_reason_generic
        VglsStringId.ERROR_UPDATE_DESCRIPTION_FORMAT -> R.string.error_update_description_format
        VglsStringId.ERROR_BROKEN_SCREEN_TITLE -> R.string.error_broken_screen_title
        VglsStringId.ERROR_BROKEN_SCREEN_DESC -> R.string.error_broken_screen_desc
        VglsStringId.ERROR_IMAGE_NETWORK -> R.string.error_image_network
        VglsStringId.ERROR_IMAGE_OFFLINE -> R.string.error_image_offline
        VglsStringId.ERROR_IMAGE_NO_INTERNET -> R.string.error_image_no_internet
        VglsStringId.ERROR_IMAGE_API_UNREACHABLE -> R.string.error_image_api_unreachable
        VglsStringId.ERROR_IMAGE_SERVER_ERROR -> R.string.error_image_server_error
        VglsStringId.ERROR_IMAGE_NOT_FOUND -> R.string.error_image_not_found
        VglsStringId.ERROR_WEBVIEW_FAILED -> R.string.error_webview_failed
        VglsStringId.TAG_CAPTION_AND_OTHERS -> R.string.tag_caption_and_others
        VglsStringId.TAG_CAPTION_SEPARATOR -> R.string.tag_caption_separator
        VglsStringId.DIFFICULTY_ONE -> R.string.difficulty_one
        VglsStringId.DIFFICULTY_TWO -> R.string.difficulty_two
        VglsStringId.DIFFICULTY_THREE -> R.string.difficulty_three
        VglsStringId.DIFFICULTY_FOUR -> R.string.difficulty_four
        VglsStringId.ACCY_OCL_CHECKBOX -> R.string.accy_ocl_checkbox
        VglsStringId.ACCY_OCL_DROPDOWN -> R.string.accy_ocl_dropdown
        VglsStringId.ACCY_OCL_RATING -> R.string.accy_ocl_rating
        VglsStringId.ACCY_OCL_SHEET_CARD -> R.string.accy_ocl_sheet_card
        VglsStringId.ACCY_OCL_SINGLE_LINE -> R.string.accy_ocl_single_line
        VglsStringId.ACCY_OCL_VALUE -> R.string.accy_ocl_value
        VglsStringId.ACCY_ST_DESC_LOADING -> R.string.accy_st_desc_loading
        VglsStringId.ACCY_ST_DESC_CHECKED -> R.string.accy_st_desc_checked
        VglsStringId.ACCY_ST_DESC_UNCHECKED -> R.string.accy_st_desc_unchecked
        VglsStringId.ACCY_CDESC_HERO_GAME -> R.string.accy_cdesc_hero_game
        VglsStringId.ACCY_CDESC_HERO_COMPOSER -> R.string.accy_cdesc_hero_composer
        VglsStringId.ACCY_CDESC_TOPBAR_BACK -> R.string.accy_cdesc_topbar_back
        VglsStringId.ACCY_CDESC_TOPBAR_MENU -> R.string.accy_cdesc_topbar_menu
        VglsStringId.ACCY_CDESC_SEARCH_BACK -> R.string.accy_cdesc_search_back
        VglsStringId.ACCY_CDESC_SEARCH_CLEAR -> R.string.accy_cdesc_search_clear
        VglsStringId.HINT_SEARCH -> R.string.hint_search
    }
