package com.vgleadsheets.ui

enum class StringId {
    APP_NAME,

    SCREEN_TITLE_BROWSE,
    SCREEN_TITLE_BROWSE_GAMES,
    SCREEN_TITLE_BROWSE_COMPOSERS,
    SCREEN_TITLE_BROWSE_TAGS,
    SCREEN_TITLE_BROWSE_ALL,
    SCREEN_TITLE_BROWSE_FAVORITES,
    SCREEN_TITLE_SEARCH,

    SCREEN_SUBTITLE_SONG_DETAIL,

    SECTION_HEADER_COMPOSERS_FROM_SONG,
    SECTION_HEADER_COMPOSERS_FROM_GAME,
    SECTION_HEADER_SONGS_FROM_GAME,
    SECTION_HEADER_SONGS_FROM_COMPOSER,
    SECTION_HEADER_GAMES_FROM_SONG,
    SECTION_HEADER_GAMES_FROM_COMPOSER,
    SECTION_HEADER_DIFFICULTY_FOR_SONG,
    SECTION_HEADER_ABOUT_SONG,

    LABEL_SONG_ALSO_KNOWN_AS,
}
